### ISSUE TITLE
bootstrap not working properly either locally or on singularity hub.

### ISSUE THREAD

**Issue by satra** [satra/om-tensorflow#1]
@vsoch - even though this container built on singularity hub it doesn't function properly. in fact i believe there were errors during the build. any chance you can take a look? it can't perform some of the change dirs.

**Comment by vsoch** [comment]
Sure thing! Here are some things that stand out:

When you have this line in the build file:

      cd ${SINGULARITY_ROOTFS}/usr/local/

The SINGULARITY_ROOTFS is the location where you are dumping stuff into the container, and referencing this place makes sense (I think) in the `%setup` but the `%post` is actually inside the container, so it is trying to go to a really weird path, and you see this error:
 
      /bin/sh: 16: cd: can't cd to /var/lib/singularity/mnt/final/usr/local/
      /bin/sh: 29: cannot create /var/lib/singularity/mnt/final/environment: Directory nonexistent

where `/var/lib/singularity/mnt/final` is the variable path that doesn't exist in the container. Generally, think about the `%post` section as a place to run commands like you were sitting inside the container, so you'd probably want this:

      cd /usr/local/

So my first suggestion would be to update the build spec to remove that variable in `%post` and try again. 

And that holds true for the end too, you can just echo into `/environment`

Let's give that a go, rebuild, then poke me again!

**Comment by satra** [comment]
closed via 30c0e9926e89abfadbb62ac06800ca2c5a77ca4b
